### ISSUE TITLE
函数导入错误

### ISSUE THREAD

**Issue by super-sweet8** [Elward-lv/LifeGame#6]
具体导入，不要直接使用“.*”
如下所示
- 不应使用 '.*' 形式的导入 - java.awt.* 。
	- 导入语句'java.awt.*' 字典顺序错误。应在'javax.swing.*'之前。
	- 导入语句'java.util.Random' 字典顺序错误。应在'javax.swing.*'之前。
	- 导入语句'java.util.concurrent.TimeUnit' 字典顺序错误。应
	 在'javax.swing.*'之前。
	- The import java.util.concurrent.TimeUnit is never used
	- 不应使用 '.*' 形式的导入 - javax.swing.* 。

**Comment by Elward-lv** [comment]
把导入语句为*号的，都修改为导入具体的包，下次一定注意，提交id：907a01a
麻烦检查一下，没有问题的情况下，关闭issue  ，幸苦了 0-0
